steps:
  # Flutter Web アプリのビルドステップ
  - name: 'cirrusci/flutter:latest'
    id: 'Build Flutter Web'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installing dependencies..."
        flutter pub get
        echo "Building Flutter web..."
        flutter build web

  # App Engine へのデプロイステップ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to App Engine'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying to App Engine..."
        gcloud app deploy app.yaml --quiet

timeout: '900s'
options:
  logging: CLOUD_LOGGING_ONLY